name: fall_2023_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # fonts:
  #   - family: SF_Pro_Display
  #     fonts:
  #       - asset: assets/fonts/SF_Pro_Display_Bold.otf
  #         weight: 700
  #   - family: SF_Pro_Text
  #     fonts:
  #       - asset: assets/fonts/SF_Pro_Text_Bold.otf
  #         weight: 700
  #       - asset: assets/fonts/SF_Pro_Text_Medium.otf
  #         weight: 500
